<?php

namespace mitgedanken\Monetary;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-13 at 22:16:04.
 */
class MonetaryStorageTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var MonetaryStorage
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new MonetaryStorage();
  }

  /**
   * @test
   * @covers mitgedanken\Monetary\MonetaryStorage::attach
   */
  public function test()
  {
    $money = new Money(20, new Currency('EUR', 'Euro'));
    $this->object->attach($money);

    $this->object->attach($money);
    $actual = $this->object->count();
    $this->assertEquals(1, $actual);

    $this->assertTrue($this->object->contains($money));

    $money = new Money(20, new Currency('USD'));
    $this->assertFalse($this->object->contains($money));

    $this->object->attach($money);
    $actual = $this->object->count();
    $this->assertEquals(2, $actual);
  }
}
