<?php

namespace mitgedanken\Monetary\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-09 at 16:49:12.
 */
class CurrencyTest extends \PHPUnit_Framework_TestCase
{

  /**
   * Test object.
   * @var Currency
   */
  private $usd;

  /**
   * Test object.
   * @var Currency
   */
  private $eur;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->usd = new Currency('USD');
    $this->eur = new Currency('EUR');
  }

  /**
   * @covers mitgedanken\Monetary\Currency::getCode
   */
  public function testGetCode()
  {
    $this->assertTrue($this->usd->getCode() === 'USD');
  }

  /**
   * @covers mitgedanken\Monetary\Currency::equals
   */
  public function testEquals()
  {
    $this->assertTrue($this->usd->equals($this->usd));
    $this->assertFalse($this->usd->equals($this->eur));
    $this->assertFalse($this->eur->equals($this->usd));
    $other = new \stdClass();
    $this->assertFalse($this->eur->equals($other));
  }

}
