<?php

namespace mitgedanken\Monetary\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-13 at 22:16:04.
 */
class MonetaryStorageTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @test
   */
  public function ImplimentationCountable()
  {
    $this->assertTrue(\is_a(new MonetaryStorage(), 'Countable'));
  }

  /**
   * @test
   * @covers mitgedanken\Monetary\MonetaryStorage::count
   */
  public function testCount()
  {
    $storage = new MonetaryStorage();
    $this->assertEquals(0, $storage->count());

    $storage->attach(new Money(1, new Currency('EUR')));
    $this->assertEquals(1, $storage->count());
    $storage->attach(new Money(1, new Currency('USD')));
    $this->assertEquals(2, $storage->count());
  }

  /**
   * @test
   * @covers mitgedanken\Monetary\MonetaryStorage::contains
   */
  public function testContains()
  {
    $eur     = new Money(1, new Currency('EUR'));
    $storage = new MonetaryStorage();

    $this->assertFalse($storage->contains($eur));
    $storage->attach($eur);
    $this->assertTrue($storage->contains($eur));
  }

}
